#!/usr/bin/env node
// Assembles the GM system-prompt content from the committed case files into a
// single generated TS module. Run this locally whenever the case changes:
//   node scripts/build-prompt.mjs
// The output (lib/game-content.generated.ts) is committed so Vercel builds from
// it directly (Vercel's root dir is app/, which does not include ../cases).
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url)); // app/scripts
const GAME = resolve(HERE, "..", ".."); // examples/berlin-bureau-game
const VAULT = join(GAME, "cases", "case-01-vault");

// Walk the player-visible vault, concatenating every markdown doc with a path
// header. Exclude machinery the player never sees.
const SKIP_DIRS = new Set([".daftari", "node_modules"]);
const SKIP_FILES = new Set(["seed.mjs"]);
function walk(dir, acc = []) {
  for (const name of readdirSync(dir).sort()) {
    if (SKIP_DIRS.has(name) || SKIP_FILES.has(name)) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, acc);
    else if (name.endsWith(".md")) acc.push(p);
  }
  return acc;
}

const files = walk(VAULT);
const vaultDocs = files
  .map((p) => {
    const rel = relative(VAULT, p);
    return `\n===== DOC: ${rel} =====\n${readFileSync(p, "utf-8").trim()}\n`;
  })
  .join("\n");

const gmSkill = readFileSync(join(GAME, "gm-skill.md"), "utf-8").trim();
const solutionKey = readFileSync(join(GAME, "cases", "case-01-solution.key.yaml"), "utf-8").trim();

const out = `// GENERATED by scripts/build-prompt.mjs — do not edit by hand.
// Regenerate after changing the case: node scripts/build-prompt.mjs
export const GM_SKILL = ${JSON.stringify(gmSkill)};
export const PLAYER_VAULT = ${JSON.stringify(vaultDocs)};
// SERVER-ONLY. Never import this into a client component.
export const SOLUTION_KEY = ${JSON.stringify(solutionKey)};
export const VAULT_FILE_COUNT = ${files.length};
`;

const libDir = join(HERE, "..", "lib");
mkdirSync(libDir, { recursive: true });
writeFileSync(join(libDir, "game-content.generated.ts"), out);
console.log(`[build-prompt] wrote lib/game-content.generated.ts from ${files.length} vault docs`);
